AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aeroreserve-seat-reservation-service

  Sample SAM Template for aeroreserve-seat-reservation-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  AeroReserveSeatReservationServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-function/
      Handler: app.lambdaHandler
      Policies: 
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:eu-north-1:058264113652:secret:zeebe-credentials-K9HCzG"
      Environment:
        Variables:
          HOME: /tmp
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        AeroReserveSeatReservationService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wakeup
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AeroReserveSeatReservationServiceApi:
    Description: API Gateway endpoint URL for Prod stage for AeroReserve Seat Reservation Service function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/wakeup/"
  AeroReserveSeatReservationServiceFunction:
    Description: AeroReserve Seat Reservation Service Lambda Function ARN
    Value: !GetAtt AeroReserveSeatReservationServiceFunction.Arn
  AeroReserveSeatReservationServiceIamRole:
    Description: Implicit IAM Role created for AeroReserve Seat Reservation Service function
    Value: !GetAtt AeroReserveSeatReservationServiceFunctionRole.Arn
